spring.application.name=auth-service
server.port=8081

# Eureka (dev local)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Datasource (dev local)
spring.datasource.url=jdbc:postgresql://localhost:5432/auth_db
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# JWT
app.jwt.secret=dW1sYW5hbHlzaXMtand0LXNlY3JldC1rZXktZm9yLWRldi1vbmx5LW11c3QtYmUtMjU2Yml0cw==
app.jwt.expiration-ms=86400000

# JSON
spring.jackson.serialization.write-dates-as-timestamps=false
