spring.application.name=analysis-service
server.port=8084

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# MinIO (dev local)
minio.endpoint=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin
minio.bucket=analysis-uploads

# JWT (same secret as other services)
app.jwt.secret=dW1sYW5hbHlzaXMtand0LXNlY3JldC1rZXktZm9yLWRldi1vbmx5LW11c3QtYmUtMjU2Yml0cw==

# Upload limits
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB

# Limite applicative (doit être <= multipart ci-dessus)
analysis.upload.max-size-mb=200

# JSON
spring.jackson.serialization.write-dates-as-timestamps=false
