spring.application.name=gateway
server.port=8080

spring.main.web-application-type=reactive

# CORS — dev (browser on localhost:3000 calls gateway directly)
app.cors.allowed-origins=http://localhost:3000

# Eureka (dev local)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Routes
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**
