package com.example.analysisservice.service;

import io.minio.*;
import io.minio.messages.Item;
import jakarta.annotation.PostConstruct;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Optional;

@Slf4j
@Service
@RequiredArgsConstructor
public class StorageService {

    private final MinioClient minioClient;

    @Value("${minio.bucket}")
    private String bucket;

    private static final DateTimeFormatter ZIP_FORMAT =
            DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH-mm-ss");
    private static final DateTimeFormatter RECORD_FORMAT =
            DateTimeFormatter.ofPattern("yyyyMMdd-HHmmss");

    @PostConstruct
    public void ensureBucketExists() {
        try {
            boolean exists = minioClient.bucketExists(BucketExistsArgs.builder().bucket(bucket).build());
            if (!exists) {
                minioClient.makeBucket(MakeBucketArgs.builder().bucket(bucket).build());
                log.info("Bucket '{}' created", bucket);
            }
        } catch (Exception e) {
            throw new IllegalStateException("Cannot connect to MinIO or create bucket: " + e.getMessage(), e);
        }
    }

    // -------------------------------------------------------------------------
    // ZIP upload
    // -------------------------------------------------------------------------

    public String upload(Long projectId, byte[] content) {
        String timestamp = LocalDateTime.now().format(ZIP_FORMAT);
        String key = "projects/" + projectId + "/" + timestamp + "-source.zip";
        put(key, content, "application/zip");
        log.info("Uploaded {} bytes → {}", content.length, key);
        return key;
    }

    public void delete(String key) {
        try {
            minioClient.removeObject(RemoveObjectArgs.builder().bucket(bucket).object(key).build());
            log.info("Deleted {}", key);
        } catch (Exception e) {
            log.warn("Could not delete {}: {}", key, e.getMessage());
        }
    }

    // -------------------------------------------------------------------------
    // Analysis history records
    // -------------------------------------------------------------------------

    /**
     * Stores a JSON analysis record in MinIO.
     *
     * Key format: projects/{projectId}/history/{recordId}-{safeName}-analysis.json
     *
     * @param recordId  timestamp string (yyyyMMdd-HHmmss) generated by the caller
     * @return the MinIO object key
     */
    public String saveRecord(Long projectId, String projectName, String recordId, byte[] jsonContent) {
        String safeName = sanitize(projectName);
        String key = "projects/" + projectId + "/history/" + recordId + "-" + safeName + "-analysis.json";
        put(key, jsonContent, "application/json");
        log.info("Saved analysis record → {}", key);
        return key;
    }

    /**
     * Lists all record keys for a project, sorted newest-first.
     */
    public List<String> listRecordKeys(Long projectId) {
        String prefix = "projects/" + projectId + "/history/";
        List<String> keys = new ArrayList<>();

        Iterable<Result<Item>> results = minioClient.listObjects(
                ListObjectsArgs.builder().bucket(bucket).prefix(prefix).recursive(true).build()
        );

        for (Result<Item> result : results) {
            try {
                keys.add(result.get().objectName());
            } catch (Exception e) {
                log.warn("Error reading MinIO listing entry: {}", e.getMessage());
            }
        }

        Collections.sort(keys, Collections.reverseOrder()); // newest timestamp first
        return keys;
    }

    /**
     * Fetches the raw JSON bytes of a record by its full MinIO key.
     */
    public byte[] getRecordContent(String key) {
        try (InputStream stream = minioClient.getObject(
                GetObjectArgs.builder().bucket(bucket).object(key).build())) {
            return stream.readAllBytes();
        } catch (Exception e) {
            throw new RuntimeException("Failed to retrieve record '" + key + "': " + e.getMessage(), e);
        }
    }

    /**
     * Finds the MinIO key of a specific record by projectId + recordId prefix.
     * Returns Optional.empty() if not found.
     */
    public Optional<String> findRecordKey(Long projectId, String recordId) {
        String prefix = "projects/" + projectId + "/history/" + recordId;
        Iterable<Result<Item>> results = minioClient.listObjects(
                ListObjectsArgs.builder().bucket(bucket).prefix(prefix).build()
        );
        for (Result<Item> result : results) {
            try {
                return Optional.of(result.get().objectName());
            } catch (Exception e) {
                log.warn("Error reading MinIO entry for recordId {}: {}", recordId, e.getMessage());
            }
        }
        return Optional.empty();
    }

    // -------------------------------------------------------------------------
    // Internal helpers
    // -------------------------------------------------------------------------

    private void put(String key, byte[] content, String contentType) {
        try {
            minioClient.putObject(PutObjectArgs.builder()
                    .bucket(bucket)
                    .object(key)
                    .stream(new ByteArrayInputStream(content), content.length, -1)
                    .contentType(contentType)
                    .build());
        } catch (Exception e) {
            throw new RuntimeException("MinIO upload failed for key '" + key + "': " + e.getMessage(), e);
        }
    }

    private String sanitize(String name) {
        String safe = name.replaceAll("[^a-zA-Z0-9]", "-").replaceAll("-{2,}", "-")
                .toLowerCase().strip();
        return safe.isEmpty() ? "projet" : safe.substring(0, Math.min(safe.length(), 40));
    }

    public static String newRecordId() {
        return LocalDateTime.now().format(RECORD_FORMAT);
    }
}
