spring.application.name=user-service
server.port=8082

# Eureka (dev local)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
