spring.application.name=diagram-service
server.port=8085

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# JWT (same secret as all other services)
app.jwt.secret=dW1sYW5hbHlzaXMtand0LXNlY3JldC1rZXktZm9yLWRldi1vbmx5LW11c3QtYmUtMjU2Yml0cw==

# JSON
spring.jackson.serialization.write-dates-as-timestamps=false
